### ISSUE TITLE
Annoying loud squelch tail

### ISSUE THREAD

**Issue by misterbig** [armel/uv-k5-firmware-custom#128]
How can we get rid of the annoying loud squelch squeaky tail?

**Comment by armel** [comment]
Check menu 41/63 STE ...

**Comment by armel** [comment]
STE was fixed in [v2.4](https://youtu.be/nrFTiYsktNw?t=313)
I wouldn't touch it again. 

Armel F4HWN

**Comment by prokrypt** [comment]
Try setting squelch to a higher number and see if it improves...

**Comment by misterbig** [comment]
what is wrong 2 radios behave the same
STE is ON sql= 9 
and 3x as loud as comparable radios

**Comment by IvanMaestroGTR** [comment]
Turns out that's just how the radio itself is capable of.
However, this firmware is ported from Egzumer, the squelch break sound is way shorter than the original QS stock firmware. As they are quite cheap and the speaker tuning basically just boosts the top end of the frequency hence louder. 

One more thing is you are actually comparing a 200-300 dollars radio to a cheap 25 dollar radio so yeah, you know it from the start.

At the end I would say...
You get what you pay ;)

**Comment by misterbig** [comment]
if you are satisfied with that
I close here

> Turns out that's just how the radio itself is capable of. However, this firmware is ported from Egzumer, the squelch break sound is way shorter than the original QS stock firmware. This radio is quite cheap and the speaker tuning basically just boosts the top end of the frequency hence louder.
> 
> One more thing is you are actually comparing a 200-300 dollars radio to a cheap 25 dollar radio so yeah, you know it from the start.
> 
> At the end I would say... You get what you pay ;)
> 
> [Just to prevent misconception] Actually squelch is technically just a filtering for how much db the RF must achieve before they activate the speaker, so it won't help with reducing the squelch sound whatsoever.
> 
> Happy Radioing! Future Ham

if you are satisfied with that
I close here

**Comment by IvanMaestroGTR** [comment]
Based on my tests, I believe there are some workarounds 

Just like the fagci spectrum analyzer single frequency monitoring mode, we can find a way to make it possible to remove squelch like that

If you don't know what I was yapping about, try monitoring your local repeater in the spectrum analyzer single frequency mode, you see what I mean

Cheers
