### ISSUE TITLE
Cannot build an image with NOAA = 1.

### ISSUE THREAD

**Issue by Jagget** [armel/uv-k5-firmware-custom#239]
In the commit d96d54cadabcfab04d0d7e7a5d9eceacb76b5d44 (Fix status bar) you've deleted the following code:
```h
#ifdef ENABLE_NOAA
	extern const uint8_t BITMAP_NOAA[11];
#endif
```
and
```c
#ifdef ENABLE_NOAA
	const uint8_t BITMAP_NOAA[11] =
	{	// "NS"
		0b00000000,
		0b01111111,
		0b00000100,
		0b00001000,
		0b00010000,
		0b01111111,
		0b00000000,
		0b01000110,
		0b01001001,
		0b01001001,
		0b00110001
	};
#endif
```
with bunch of other definitions. 

The NOAA code do rely on this constant:
```c
#ifdef ENABLE_NOAA
    if (gIsNoaaMode) { // NOASS SCAN indicator
        memcpy(line + x, BITMAP_NOAA, sizeof(BITMAP_NOAA));
        x1 = x + sizeof(BITMAP_NOAA);
    }
    x += sizeof(BITMAP_NOAA);
#endif
```

Can you please fix NOAA functionality?

**Comment by armel** [comment]
First off all, hello...

You know, I've been working on this firmware for 9 months. And I have removed support for features like NOAA, SCRAMBLER or DTMF CALLING.

Why did I do this? Because a feature like NOAA is not available in the region where I live (Europe). I can't maintain something I can't test, and I can't control the side effects of everything I've added since then. As for DTMF CALLING or SCRAMBLER, these features are forbidden by regulations in many countries.

Apart from that, I can assure you that this firmware works quite well. 

Armel F4HWN

**Comment by Jagget** [comment]
I got that. Thanks for explanation. But you still have this build flag in the Make file. And since I'm form the USA, I thought I could have your changes **and** NOAA notifications, but looks like I can't :/

**Comment by armel** [comment]
I think it should be fairly easy to get NOAA support working again. But it's hard for me to do, as I can't test it. Beware also of the memory space this feature will occupy. You'll probably have to turn off other features to fit this into memory. 

Armel F4HWN.

**Comment by Jagget** [comment]
Roger that. Thanks

**Comment by armel** [comment]
You're welcome ;)
