### ISSUE TITLE
TxDCS/RxDCS settings not saved?

### ISSUE THREAD

**Issue by MWP** [armel/uv-k5-firmware-custom#248]
Hi all,
Is it correct that DCS settings are not saved on power-off?
As in, turn radio on, set TxDCS/RxDCS, all ok, turn radio off, then back on, DCS settings are now OFF.
Thanks.

**Comment by armel** [comment]
Hello,

The reason is : in memory channel mode, TxDCS/RxDCS is a "_per channel_" parameter. You can change it from the radio. But if you want this change to persist (after changing channel, restarting the pocket, etc.), you **need to save the memory channel again** (via menu 17 ChSave). **Otherwise, the change is only temporary**, as you've seen for yourself.

The same behavior applies to mode, power, W/N, BusyCL, ... and all “per channel” parameters. This is normal usage on all (commercial) transceivers.

Regards,

Armel F4HWN.
