### ISSUE TITLE
Not compiling correctly

### ISSUE THREAD

**Issue by lohtse** [armel/uv-k5-firmware-custom#297]
Not compiling with set up I choose... EG nolonger can create one with FM radio only Spectrum

This is with featrev3   and commits as of this time and date

**Comment by armel** [comment]
First of all, Hi.

Please don't open an issue concerning the **feature_update_v3** branch, which is a development branch, otherwise it becomes impossible to manage. 

I don't know how you compile your custom version, but if you take a look to this [commit](https://github.com/armel/uv-k5-firmware-custom/commit/7edfb2331c2174fdb716f249c1faf01cd840a6b2) I removed old `compile-with-docker.sh` shell script and replace it by a new one. 

Finally, note that only 31 bytes were left free in the Voxless version. So you're likely to run into memory space problems very quickly. 

Armel F4HWN.

**Comment by armel** [comment]
Again, take a look to the`compile-with-docker.sh` script !

You want to compile _broadcast_ version ? Use the command `compile-with-docker.sh broadcast`
You want to compile _bandscope_ version ? Use the command `compile-with-docker.sh bandscope`
You want to compile _voxless_ version ? Use the command `compile-with-docker.sh voxless`
You want to compile _all_ versions ? Use the command `compile-with-docker.sh all`

By the way, _all_ versions compile as before...

```
❯ ./compile-with-docker.sh all
rm: /Users/armel/Dropbox/uv-k5-firmware-custom/compiled-firmware/*: No such file or directory
[+] Building 3.3s (15/15) FINISHED                                                      docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                    0.0s
 => => transferring dockerfile: 445B                                                                    0.0s
 => WARN: FromPlatformFlagConstDisallowed: FROM --platform flag should not use constant value "amd64"   0.0s
 => [internal] load metadata for docker.io/library/archlinux:latest                                     1.2s
 => [internal] load .dockerignore                                                                       0.0s
 => => transferring context: 2B                                                                         0.0s
 => [ 1/10] FROM docker.io/library/archlinux:latest@sha256:876f1f601e5fe6ceda682ac9b0a8df06be695fe9e2c  0.0s
 => [internal] load build context                                                                       0.4s
 => => transferring context: 2.03MB                                                                     0.3s
 => CACHED [ 2/10] RUN pacman -Syyu base-devel --noconfirm                                              0.0s
 => CACHED [ 3/10] RUN pacman -Syyu arm-none-eabi-gcc --noconfirm                                       0.0s
 => CACHED [ 4/10] RUN pacman -Syyu arm-none-eabi-newlib --noconfirm                                    0.0s
 => CACHED [ 5/10] RUN pacman -Syyu git --noconfirm                                                     0.0s
 => CACHED [ 6/10] RUN pacman -Syyu python-pip --noconfirm                                              0.0s
 => CACHED [ 7/10] RUN pacman -Syyu python-crcmod --noconfirm                                           0.0s
 => CACHED [ 8/10] WORKDIR /app                                                                         0.0s
 => [ 9/10] COPY . .                                                                                    0.7s
 => [10/10] RUN git submodule update --init --recursive                                                 0.7s
 => exporting to image                                                                                  0.3s
 => => exporting layers                                                                                 0.3s
 => => writing image sha256:4c71e7d7052c79534e53a595bb1573aebf3d073a3403f631d1b5e9547283410e            0.0s
 => => naming to docker.io/library/uvk5                                                                 0.0s

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/tcbf5exs65wlil4yrnu2jpr0y

 1 warning found (use docker --debug to expand):
 - FromPlatformFlagConstDisallowed: FROM --platform flag should not use constant value "amd64" (line 1)

What's next:
    View a summary of image vulnerabilities and recommendations → docker scout quickview
Bandscope compilation...
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
   text	   data	    bss	    dec	    hex	filename
  61188	     52	   3392	  64632	   fc78	f4hwn.bandscope
Broadcast compilation...
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
   text	   data	    bss	    dec	    hex	filename
  59352	     20	   3036	  62408	   f3c8	f4hwn.broadcast
Voxless compilation...
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
   text	   data	    bss	    dec	    hex	filename
  61356	     52	   3340	  64748	   fcec	f4hwn.voxless
```

Armel F4HWN.

**Comment by armel** [comment]
> does the all command allow custom setup??
> and why the change to make things complicated???

Are you serious?

So yes, you can make your custom settings. You just need to plug your brain. Again, take a look to the `compile-with-docker.sh` script ! Third time I've told you. 

And no, it's not more complicated ! It's more flexible and it saves me lot's of time.

Armel F4HWN.

**Comment by armel** [comment]
So you use Windows? Well, let's be clear, I haven't changed anything in the compilation process of this firmware, under Windows. So, your problem is somewhere else. But remember... there were only 31 bytes were left free in the Voxless version.

**Comment by armel** [comment]
I don't understand a word. What command do you use to compile? And please send me your complete Makefile (in attachement). It'll be quicker...

**Comment by armel** [comment]
Ok, I understand that what you don't understand.
Again, take a look to the `compile-with-docker.sh` script ! Fourth time I've told you :)

You could edit Makefile and change some settings. But the script `compile-with-docker.sh`will eventually rewrite some of them. Take a look to Voxless section...

```
voxless() {
    echo "Voxless compilation..."
    docker run --rm -v "${PWD}/compiled-firmware:/app/compiled-firmware" $IMAGE_NAME /bin/bash -c "cd /app && make -s \
        ENABLE_SPECTRUM=1 \
        ENABLE_FMRADIO=1 \
        ENABLE_VOX=0 \
        ENABLE_AIRCOPY=0 \
        ENABLE_AUDIO_BAR=0 \
        ENABLE_FEAT_F4HWN_SPECTRUM=0 \
        ENABLE_NOAA=0 \
        ENABLE_FEAT_F4HWN_RESTORE_SCAN=0 \
        ENABLE_FEAT_F4HWN_CHARGING_C=0 \
        ENABLE_FEAT_F4HWN_NARROWER=0 \
        TARGET=f4hwn.voxless \
        && cp f4hwn.voxless* compiled-firmware/"
} 
```

So even if you set ENABLE_FMRADIO to 0 and ENABLE_SPECTRUM to 0 **in the Makefile**, they will be rewritten and set to 1 **by the compilation script**. That's why your Voxless compilation goes out of memory space...

Well, take the latest version of the feature_update_v3 branch and now use: `compile-with-docker.sh custom`!
With this custom option, the script only builds what's in your Makefile and doesn't overwrite any parameters. 

Seriously, all this time for this... Since the beginning I said that I don't know how you compile your custom version, but if you take a look to this [commit](https://github.com/armel/uv-k5-firmware-custom/commit/7edfb2331c2174fdb716f249c1faf01cd840a6b2) I removed old compile-with-docker.sh shell script and replace it by a new one... That was the solution. 

Armel F4HWN.
